import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProviderNextUI } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full`}>
        <ProviderNextUI>
          <main className="h-full">
            {children}
          </main>
        </ProviderNextUI>
      </body>
    </html>
  );
}
