FROM node:20.11.1

WORKDIR /task/front

COPY ./front/package.json .
COPY ./front/package-lock.json* .

RUN npm install

COPY ./front/. .

RUN npm run build

EXPOSE 3030

# npm run start:prod
CMD ["npm", "run", "start"]