FROM node:20.11.1

WORKDIR /task/api

COPY ./api/package.json .

RUN npm install

COPY ./api/. .

RUN npm run build

RUN rm -rf ./src

EXPOSE 3000

# npm run start:prod
CMD ["npm", "run", "start:prod"]